// components/layout/Header.vue
<template>
    <header class="container mx-auto px-2 md:px-12 lg:px-16 xl:px-20">
        <div
            class="flex justify-between md:justify-start items-center border-black border-b-2 py-3 md:py-5"
        >
            <nav class="hidden md:flex space-x-6 tracking-wide text-xs text-black uppercase">
                <NuxtLink title="home" to="/" class="font-bold">Home</NuxtLink>
                <NuxtLink title="posts" to="/posts" class="font-bold">Posts</NuxtLink>
                <NuxtLink title="about" to="/about/" class="font-bold">About</NuxtLink>
                <NuxtLink title="resource" to="/resource" class="font-bold">Resource</NuxtLink>
            </nav>
            <div class="-my-2 md:hidden">
                <button
                    type="button"
                    aria-label="openMenu"
                    @click="isOpen = !isOpen"
                    class="m-2 items-center justify-center focus:outline-none"
                >
                    <svg
                        class="h-6 w-6"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="black"
                        aria-hidden="true"
                    >
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M4 6h16M4 12h16M4 18h16"
                        />
                    </svg>
                </button>
            </div>
            <div class="flex items-center justify-end md:flex-1">
                <a
                    title="subscribe"
                    class="text-gray-600 flex items-center uppercase text-xs font-bold tracking-wide"
                    href="#"
                    rel="noopener"
                    aria-label="subscribe"
                >
                    <svg
                        style="display: unset"
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="feather feather-mail mr-1"
                    >
                        <path
                            d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"
                        />
                        <polyline points="22,6 12,13 2,6" />
                    </svg>
                    Subscribe
                </a>
                <a
                    title="searchOpen"
                    class="ml-8 mr-2 lg:mr-0"
                    href="javascript:;"
                    aria-label="searchOpen"
                    @click="isSearch = !isSearch"
                >
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="18"
                        height="18"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.5"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="feather feather-search"
                    >
                        <circle cx="11" cy="11" r="8" />
                        <line x1="21" y1="21" x2="16.65" y2="16.65" />
                    </svg>
                </a>
            </div>
        </div>

        <!-- <MobileMenu v-show="isOpen" @menuAction="menuOption" /> -->
        <div class="flex justify-center items-center h-32 md:h-40">
            <NuxtLink
                to="/"
                class="text-4xl tracking-widest font-black uppercase text-black text-center"
            >
                <figure class="inline-flex justify-center">
                    <!-- <nuxt-picture src="https://cdn.leafage.top/logo-only.png" alt="Leafage" width="64" height="64"/> -->
                </figure>
                <h1>Leafage</h1>
            </NuxtLink>
        </div>
        <!-- <Search v-show="isSearch" @searchOption="searchOption" /> -->
    </header>
</template>

<script lang="ts" setup>
const isOpen = ref(false)
const isSearch = ref(false)
</script>

// app/ui/header.tsx
'use client'

import { usePathname } from 'next/navigation'
import Link from 'next/link'
import Image from 'next/image'
import { clsx } from 'clsx'
import { MagnifyingGlassIcon, Bars3Icon } from '@heroicons/react/24/outline'
import ThemeSwitch from '@/app/ui/theme-switch'
import { headerList } from '@/app/lib/data'

export default function Header() {
  const pathname = usePathname()

  return (
    <header className="container mx-auto p-4 flex justify-between items-center">
      <div className="inline-flex items-center justify-between w-full lg:w-1/4">
        <Link href="/" >
          <Image
            src="/logo.png"
            className="rounded-full"
            alt="logo"
            width={40}
            height={40}
            style={{
              objectFit: 'contain',
              objectPosition: "center"
            }} />
        </Link>
        <button title='bar' type='button' className="xl:hidden focus:outline-none">
          <Bars3Icon className="h-6 w-6 text-neutral-700 dark:text-neutral-300" aria-hidden="true" />
        </button>
      </div>
      <nav className='hidden lg:inline-flex'>
        <ul className="flex justify-between items-center space-x-6">
          {headerList.map(item => (
            <Link
              href={item.path}
              className={clsx('text-md xl:text-base py-2 transition-transform duration-200 font-semibold hover:text-lime-600',
                pathname === item.path ? 'text-lime-600' : 'text-neutral-700 dark:text-neutral-300')}
              rel="noopener noreferrer"
              id={item.title}
              aria-expanded="false"
              key={item.title}>
              <span>{item.title}</span>
            </Link>))}
        </ul>
      </nav>
      <div className="hidden lg:inline-flex lg:w-1/4 items-center justify-end space-x-1">
        <ThemeSwitch />
        <div className="relative">
          <button type="button" title='search_button' className="w-9 h-9 rounded-full hover:bg-lime-50 dark:hover:bg-neutral-800 focus:outline-none flex items-center justify-center transition-colors duration-200" id="dark" aria-expanded="false">
            <MagnifyingGlassIcon className="h-5 w-5 text-neutral-700 dark:text-neutral-300" aria-hidden="true" />
          </button>
        </div>
        <div className="relative">
          <Link href="https://github.com/little3201" target="_blank" className="w-9 h-9 rounded-full text-neutral-700 dark:text-neutral-300 hover:bg-lime-50 dark:hover:bg-neutral-800 focus:outline-none flex items-center justify-center transition-colors duration-200" id="search" type="button" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
          </Link>
        </div>
      </div>
    </header >
  )
}
