// app/docs/[slug]/page.tsx
// Return a list of `params` to populate the [slug] dynamic segment
export async function generateStaticParams() {

  return [{
    slug: '1',
  }]
}

export default function Page() {
  return (
    <article className="flex min-h-screen flex-col items-center justify-center overflow-hidden py-8 md:py-16">
      <div className="w-full grow rounded bg-white md:shadow-2xl dark:bg-neutral-900 dark:shadow-neutral-500 max-w-4xl p-2 md:py-16">
        <div
          className='mx-auto prose prose-green lg:prose-lg dark:prose-invert'
          dangerouslySetInnerHTML={{ __html: 'xxxx内容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试容测试' }}
        />
      </div>
    </article>
  )
}

// app/pages/blogs/[...slug].vue
<script setup lang="ts">
const route = useRoute()
const { data: navigation } = await useAsyncData(() => queryCollectionNavigation('blogs'))

const { data: page } = await useAsyncData(route.path, () => queryCollection('blogs').path(route.path).first())
if (!page.value) {
  throw createError({ statusCode: 404, statusMessage: 'Page not found', fatal: true })
}
</script>

<template>
  <section class="container mx-auto flex space-x-12 p-6">
    <div
      class="hidden h-full max-h-screen w-64 shrink-0 overflow-auto rounded-sm bg-gray-50 dark:bg-neutral-900 lg:block">
      <EssentialLink :items="navigation" />
    </div>

    <div class="flex h-full flex-1 flex-col items-center overflow-hidden lg:pb-16">
      <h1 className="text-2xl mx-auto max-w-2xl font-semibold tracking-tight text-center lg:text-4xl">
        {{ page?.title }}
      </h1>
      <div class="w-full grow rounded-sm md:shadow-lg dark:shadow-gray-700/40 max-w-5xl md:py-16">
        <ContentRenderer v-if="page" :value="page"
          class="prose ma-auto max-w-3xl dark:prose-invert prose-pre:bg-gray-100 dark:prose-pre:bg-neutral-800 mx-auto" />
      </div>
    </div>
  </section>
</template>
