// src/app/blogs/page.tsx
import Link from 'next/link'
import { queryCollectionNavigation } from '@/lib/api'

export default async function Index() {
  const navigation = await queryCollectionNavigation('blogs')

  return (
    <div className="container mx-auto px-4 lg:px-8 lg:py-8">
      <div className="grid grid-cols-1 gap-x-8 gap-y-6 lg:grid-cols-3 dark:border-gray-700">
        {navigation.map((item) => (
          <article key={item.slug} className="flex max-w-xl flex-col items-start justify-between border rounded-2xl p-4">
            <div className="flex items-center text-xs">
              {item.date && (
                <time dateTime={item.date}>
                  {new Intl.DateTimeFormat('en-US', {
                    year: 'numeric',
                    month: 'short',
                    day: 'numeric',
                  }).format(new Date(item.date))}
                </time>
              )}
            </div>
            <div className="group relative grow">
              <h3 className="mt-3 text-lg/6 font-semibold text-gray-900 group-hover:text-lime-600 dark:text-white dark:group-hover:text-gray-300">
                <Link href={item.path}>
                  <span className="absolute inset-0" />
                  {item.title}
                </Link>
              </h3>
              <div className="flex flex-wrap space-x-2 my-2">
                {item.seo.tags?.map((tag) => <span key={tag} className="finline-block text-xs font-medium tracking-wider uppercase text-lime-600">{tag}</span>)}
              </div>
              <p className="mt-3 line-clamp-3 text-sm/6 text-gray-600 dark:text-gray-400">{item.excerpt}</p>
            </div>
          </article>
        ))}
      </div>
    </div>
  )
}

// app/pages/blogs/index.vue
<script setup lang="ts">
const { data: navigation } = await useAsyncData('navigation', () => queryCollectionNavigation('blogs'))
const { data: blogs } = await useAsyncData(() => queryCollection('blogs')
  .select('title', 'path', 'date', 'description', 'seo', 'id')
  .order('date', 'DESC')
  .all())
</script>

<template>
  <section class="container mx-auto flex space-x-12 p-6">
    <div class="hidden h-full max-h-screen w-64 shrink-0 overflow-auto rounded-sm bg-gray-50 dark:bg-gray-900 lg:block">
      <EssentialLink :items="navigation" />
    </div>
    <ul>
      <li v-for="item in blogs" :key="item.title"
        class="flex flex-col space-y-2 xl:space-y-0 p-5 rounded-sm hover:bg-gray-50 dark:hover:bg-black/80 group">
        <dl>
          <dt class="sr-only">Published on</dt>
          <dd class="text-sm font-medium leading-6 text-gray-500 dark:text-gray-400">
            <time dateTime={blog.date}>{{ new Intl.DateTimeFormat('en-US',
              { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(item.date)) }}
            </time>
          </dd>
        </dl>
        <div class="space-y-3">
          <div>
            <h2 class="text-xl font-bold leading-8 tracking-tight">
              <NuxtLink :to="item.path" class="text-gray-900 group-hover:text-lime-600 dark:text-gray-100">
                {{ item.title }}
              </NuxtLink>
            </h2>
            <div class="flex flex-wrap space-x-2 mt-1">
              <span v-for="tag in item.seo.tags" :key="tag"
                class="finline-block text-xs tracking-wider bg-gray-200 text-lime-600 px-2 py-1 rounded-xl">
                {{ tag }}
              </span>
            </div>
          </div>
          <div class="text-sm text-gray-500 dark:text-gray-400">
            {{ item.description }}
          </div>
        </div>
      </li>
    </ul>
  </section>
</template>
