// src/app/_components/header.tsx
'use client'

import { usePathname } from 'next/navigation'
import Link from 'next/link'
import Image from 'next/image'
import { clsx } from 'clsx'
import { MagnifyingGlassIcon, Bars3Icon } from '@heroicons/react/24/outline'
import ThemeSwitch from '@/app/_components/theme-switch'
import { headerList } from '@/lib/data'

export default function Header() {
  const pathname = usePathname()

  return (
    <header className="container mx-auto p-4 flex justify-between items-center">
      <div className="inline-flex items-center justify-between w-full lg:w-1/4">
        <Link href="/" >
          <Image
            src="/logo.png"
            className="rounded-full"
            alt="logo"
            width={40}
            height={40}
            style={{
              objectFit: 'contain',
              objectPosition: "center"
            }} />
        </Link>
        <button title='bar' type='button' className="xl:hidden focus:outline-none">
          <Bars3Icon className="h-6 w-6 text-neutral-700 dark:text-neutral-300" aria-hidden="true" />
        </button>
      </div>
      <nav className='hidden lg:inline-flex'>
        <ul className="flex justify-between items-center space-x-6">
          {headerList.map(item => (
            <Link
              href={item.path}
              className={clsx('text-md xl:text-base py-2 transition-transform duration-200 font-semibold hover:text-lime-600',
                pathname === item.path ? 'text-lime-600' : 'text-neutral-700 dark:text-neutral-300')}
              rel="noopener noreferrer"
              id={item.title}
              aria-expanded="false"
              key={item.title}>
              <span>{item.title}</span>
            </Link>))}
        </ul>
      </nav>
      <div className="hidden lg:inline-flex lg:w-1/4 items-center justify-end space-x-1">
        <div className="relative">
          <button type="button" title='search_button' className="w-9 h-9 rounded-full hover:bg-lime-50 dark:hover:bg-neutral-800 focus:outline-none flex items-center justify-center transition-colors duration-200" id="dark" aria-expanded="false">
            <MagnifyingGlassIcon className="h-5 w-5 text-neutral-700 dark:text-neutral-300" aria-hidden="true" />
          </button>
        </div>
        <ThemeSwitch />
        <div className="relative">
          <Link href="https://github.com/little3201" target="_blank" className="w-9 h-9 rounded-full text-neutral-700 dark:text-neutral-300 hover:bg-lime-50 dark:hover:bg-neutral-800 focus:outline-none flex items-center justify-center transition-colors duration-200" id="search" type="button" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
          </Link>
        </div>
      </div>
    </header >
  )
}

// components/templates/Header.vue
<template>
  <header>
    <div class="container mx-auto">
      <div
        class="flex justify-between items-center border-black py-3 md:py-5 md:justify-start"
        style="border-bottom-width: 3px"
      >
        <div class="-my-2 md:hidden">
          <button
            type="button"
            @click="isOpen = !isOpen"
            class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
          >
            <svg
              class="h-6 w-6"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="black"
              aria-hidden="true"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 6h16M4 12h16M4 18h16"
              />
            </svg>
          </button>
        </div>
        <nav class="hidden md:flex space-x-6 tracking-wide">
          <nuxt-link to="/" class="text-xs font-extrabold uppercase text-black">
            Home
          </nuxt-link>
          <nuxt-link
            to="/portfolio"
            class="text-xs font-extrabold uppercase text-black"
          >
            Portfolio
          </nuxt-link>
          <nuxt-link
            to="/about"
            class="text-xs font-extrabold uppercase text-black"
          >
            About
          </nuxt-link>
          <nuxt-link
            to="/contact"
            class="text-xs font-extrabold uppercase text-black"
          >
            Contact
          </nuxt-link>
        </nav>
        <div class="flex items-center justify-end md:flex-1">
          <a
            class="text-gray-600 flex items-center uppercase text-xs font-bold tracking-wide"
            href="#"
            title=""
          >
            <svg
              style="display: unset"
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-mail mr-1"
            >
              <path
                d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"
              ></path>
              <polyline points="22,6 12,13 2,6"></polyline>
            </svg>
            Subscribe
          </a>
          <a class="ml-8 mr-2 lg:mr-0" href="#" title="">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="#6d6d6d"
              stroke-width="1.5"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="feather feather-search"
            >
              <circle cx="11" cy="11" r="8"></circle>
              <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
            </svg>
          </a>
        </div>
      </div>
      <div class="flex justify-center items-center h-32 md:h-40">
        <nuxt-link
          to="/"
          class="text-4xl tracking-widest font-black uppercase text-black"
        >
          <img src="/logo-only.png" class="w-16 mx-auto" />
          <h1>Leafage</h1>
        </nuxt-link>
      </div>
      <SideMenu v-show="isOpen" />
    </div>
  </header>
</template>

<script lang="ts">
import { defineComponent } from "@vue/composition-api";

export default defineComponent({
  name: "Header",

  data() {
    return {
      isOpen: false,
    };
  },
});
</script>
